# Generated by Django 5.2.17 on 2026-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.CharField(choices=[('EXENTO', 'Exento'), ('5', '5%'), ('10', '10%')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
    ]
